## BASIC OPERATIONS OF VECTORS

In [6]:
import numpy as np
A = np.array([[1,1], [1,0]])
B = np.array([[1,0], [0,1]])
C = A-B
print(A-B)

[[ 0  1]
 [ 1 -1]]


## ADDITION, SUBTRACTION AND MULTIPLICATION OF SCALARS

In [9]:
D = C.copy()
print(D + 2)

[[2 3]
 [3 1]]


In [8]:
print(D * -2)

[[ 0 -2]
 [-2  2]]


In [10]:
print(D - 2)

[[-2 -1]
 [-1 -3]]


## PERFORMING MATRIX MULTIPLICATION

In [11]:
X = np.array([[4, 5], [2, 4], [3, 3]])
b = [3, -2]
X.dot(b) #or
print(X @ b)

[ 2 -2  3]


In [12]:
X = np.array([[4, 5], [2, 4], [3, 3]])
B = np.array([[3,-2], [-2, 5]])
print(X @ B)

[[ 2 17]
 [-2 16]
 [ 3  9]]


## ADVANCED MATRIX OPERATION

In [13]:
A = np.array([[1, 2, 3], [2, 3, 5], [7, 11, 13]])
print(A.transpose())

[[ 1  2  7]
 [ 2  3 11]
 [ 3  5 13]]


In [14]:
D = A.copy()
print(D)

[[ 1  2  3]
 [ 2  3  5]
 [ 7 11 13]]


In [15]:
##inveerse of a Matrix
print(np.linalg.inv(A))

[[-3.2  1.4  0.2]
 [ 1.8 -1.6  0.2]
 [ 0.2  0.6 -0.2]]


In [16]:
X = np.array([[2, 3, 4], [-2, 3, 4], [3, -4, 5]])
print(X)
print(X.shape)

[[ 2  3  4]
 [-2  3  4]
 [ 3 -4  5]]
(3, 3)


In [17]:
X = np.array([[2, 3, 4, -2, 3, 4, 3, -4, 5]]).reshape(3, 3)
print(X)

[[ 2  3  4]
 [-2  3  4]
 [ 3 -4  5]]
